/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        'on-surface-variant': '#424656',
        'on-primary-fixed': '#00174c',
        'on-tertiary-fixed-variant': '#832700',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary-container': '#ffefeb',
        'tertiary-container': '#c73f00',
        tertiary: '#9d3000',
        'on-secondary': '#ffffff',
        'on-primary-container': '#f1f2ff',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed-dim': '#ffb59d',
        'tertiary-fixed': '#ffdbd0',
        'inverse-on-surface': '#eff1f3',
        'secondary-container': '#d5e3fc',
        'on-background': '#191c1e',
        'inverse-surface': '#2d3133',
        secondary: '#515f74',
        'secondary-fixed': '#d5e3fc',
        'surface-variant': '#e0e3e5',
        'on-surface': '#191c1e',
        'surface-dim': '#d8dadc',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        surface: '#f7f9fb',
        'surface-tint': '#0052dc',
        'on-primary-fixed-variant': '#003da9',
        'inverse-primary': '#b4c5ff',
        'surface-bright': '#f7f9fb',
        'on-secondary-container': '#57657a',
        outline: '#737687',
        'on-secondary-fixed-variant': '#3a485b',
        'on-secondary-fixed': '#0d1c2e',
        'on-primary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-fixed': '#390c00',
        'surface-container-low': '#f2f4f6',
        'primary-fixed-dim': '#b4c5ff',
        'outline-variant': '#c2c6d9',
        'primary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b9c7df',
        primary: '#004bcb',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#0561ff',
        'surface-container': '#eceef0',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
